[tools]
bun = "1.3.6"

[tasks]
"install:bun" = "bun install"
install = { depends = ["install:*"] }

"codegen:paraglide" = "bun run paraglide:compile"
codegen = { depends = ["codegen:*"] }

"lint:eslint" = "eslint ."
"lint:prettier" = "prettier --check ."
"lint:check" = "bun run check"
lint = { depends = ["lint:*"] }

"fmt:prettier" = "prettier --write ."
fmt = { depends = ["fmt:*"] }

"test:unit" = "echo 'No tests found'"
"test:build" = "bun run build"
test = { depends = ["test:*"] }

build = "bun run build"

ci = { depends = ["lint", "test"] }
